name: Cloudflare R2 Usage

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  cloudflare-r2-usage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get R2 bucket usage
        id: get_r2-bucket-usage
        env:
          ACCOUNT_ID: ${{ secrets.account_id }}
          BUCKET_NAME: ${{ secrets.bucket_name }}
          API_TOKEN: ${{ secrets.api_token }}
        run: |
          RESPONSE=$(curl -X GET "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/r2/buckets/$BUCKET_NAME/usage" \
          -H "Authorization: Bearer $API_TOKEN" \
          -H "Content-Type:application/json")
          echo "RESPONSE_JSON=$RESPONSE" >> $GITHUB_ENV

      - name: Check success and convert JSON to CSV
        run: |
          SUCCESS=$(echo $RESPONSE_JSON | jq .success)
          if [ "$SUCCESS" != "true" ]; then
            echo "API call failed."
            exit 1
          else
            if [ ! -f output.csv ]; then
              echo 'end,payloadSize,metadataSize,objectCount,uploadCount' >> output.csv
            fi
            echo $RESPONSE_JSON | jq -r '.result | [.end, .payloadSize, .metadataSize, .objectCount, .uploadCount] | @csv' >> output.csv
          fi
      
      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update output.csv"
          git push
